import { v4 as uuidv4 } from "uuid"

export const mockAnalytics = {
  totalSales: 125000,
  totalOrders: 850,
  averageOrderValue: 147.06,
  returnRate: 0.05,
  topSellingProduct: "Wireless Earbuds",
  mostReturnedProduct: "Smartwatch X",
}

export const mockRestockRecommendations = [
  {
    id: uuidv4(),
    product_id: "prod_001",
    product_name: "Wireless Earbuds",
    current_stock: 50,
    recommended_quantity: 200,
    confidence_score: 0.95,
    urgency: "high" as const,
    predicted_stockout_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(), // 7 days from now
    supplier_id: "supp_001",
    supplier_name: "Tech Supply Co.",
    ai_reasoning: "High sales velocity and low current stock. Predicted stockout in 7 days.",
    status: "active" as const,
  },
  {
    id: uuidv4(),
    product_id: "prod_002",
    product_name: "Smartwatch X",
    current_stock: 120,
    recommended_quantity: 100,
    confidence_score: 0.88,
    urgency: "medium" as const,
    predicted_stockout_date: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(), // 20 days from now
    supplier_id: "supp_002",
    supplier_name: "Wearable Innovations",
    ai_reasoning: "Steady sales, but upcoming seasonal demand spike expected. Replenish soon.",
    status: "active" as const,
  },
  {
    id: uuidv4(),
    product_id: "prod_003",
    product_name: "Portable Bluetooth Speaker",
    current_stock: 300,
    recommended_quantity: 50,
    confidence_score: 0.75,
    urgency: "low" as const,
    predicted_stockout_date: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(), // 45 days from now
    supplier_id: "supp_001",
    supplier_name: "Tech Supply Co.",
    ai_reasoning: "Stable demand, current stock sufficient for next month. Small top-up recommended.",
    status: "active" as const,
  },
  {
    id: uuidv4(),
    product_id: "prod_004",
    product_name: "Ergonomic Office Chair",
    current_stock: 80,
    recommended_quantity: 70,
    confidence_score: 0.92,
    urgency: "high" as const,
    predicted_stockout_date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(), // 10 days from now
    supplier_id: "supp_003",
    supplier_name: "Office Comforts Inc.",
    ai_reasoning: "Consistent demand, stock levels dropping faster than anticipated.",
    status: "active" as const,
  },
]

export const mockSuppliers = [
  {
    id: "supp_001",
    name: "Tech Supply Co.",
    email: "contact@techsupply.com",
    phone: "123-456-7890",
    address: "101 Tech Lane, Silicon Valley, CA",
    region: "North America",
    avg_delivery_days: 7,
    price_rating: 4,
    sla_rating: 5,
    rating: 4.5,
    price_competitiveness: 90,
    reliability_score: 95,
    total_orders: 150,
  },
  {
    id: "supp_002",
    name: "Wearable Innovations",
    email: "sales@wearableinnovations.com",
    phone: "987-654-3210",
    address: "202 Gadget Blvd, Innovation City, NY",
    region: "North America",
    avg_delivery_days: 10,
    price_rating: 3,
    sla_rating: 4,
    rating: 3.5,
    price_competitiveness: 75,
    reliability_score: 88,
    total_orders: 80,
  },
  {
    id: "supp_003",
    name: "Office Comforts Inc.",
    email: "info@officecomforts.com",
    phone: "555-123-4567",
    address: "303 Chair St, Business Park, TX",
    region: "North America",
    avg_delivery_days: 14,
    price_rating: 5,
    sla_rating: 4,
    rating: 4.5,
    price_competitiveness: 95,
    reliability_score: 92,
    total_orders: 60,
  },
  {
    id: "supp_004",
    name: "Global Electronics Ltd.",
    email: "support@globalelectronics.com",
    phone: "44-20-7123-4567",
    address: "404 Circuit Lane, London, UK",
    region: "Europe",
    avg_delivery_days: 21,
    price_rating: 4,
    sla_rating: 3,
    rating: 3.5,
    price_competitiveness: 80,
    reliability_score: 70,
    total_orders: 120,
  },
]

export const mockBuyers = [
  {
    id: "buyer_001",
    name: "Alice Johnson",
    email: "alice.j@example.com",
    phone: "111-222-3333",
    address: "123 Main St, Anytown, USA",
    created_at: new Date("2023-01-15").toISOString(),
  },
  {
    id: "buyer_002",
    name: "Bob Williams",
    email: "bob.w@example.com",
    phone: "444-555-6666",
    address: "456 Oak Ave, Somewhere, USA",
    created_at: new Date("2023-02-20").toISOString(),
  },
  {
    id: "buyer_003",
    name: "Charlie Brown",
    email: "charlie.b@example.com",
    phone: "777-888-9999",
    address: "789 Pine Ln, Nowhere, USA",
    created_at: new Date("2023-03-10").toISOString(),
  },
]

export const mockProducts = [
  {
    id: "prod_001",
    name: "Wireless Earbuds",
    description: "High-fidelity wireless earbuds with noise cancellation.",
    price: 79.99,
    category: "Electronics",
    sku: "ELEC-ERB-001",
    stock_quantity: 50,
    supplier_id: "supp_001",
    created_at: new Date("2023-01-01").toISOString(),
  },
  {
    id: "prod_002",
    name: "Smartwatch X",
    description: "Advanced smartwatch with health tracking and long battery life.",
    price: 199.99,
    category: "Wearables",
    sku: "WEAR-SMW-002",
    stock_quantity: 120,
    supplier_id: "supp_002",
    created_at: new Date("2023-01-05").toISOString(),
  },
  {
    id: "prod_003",
    name: "Portable Bluetooth Speaker",
    description: "Compact and powerful speaker with deep bass.",
    price: 49.99,
    category: "Audio",
    sku: "AUDI-SPK-003",
    stock_quantity: 300,
    supplier_id: "supp_001",
    created_at: new Date("2023-01-10").toISOString(),
  },
  {
    id: "prod_004",
    name: "Ergonomic Office Chair",
    description: "Adjustable office chair for maximum comfort and support.",
    price: 249.99,
    category: "Office Furniture",
    sku: "FURN-CHR-004",
    stock_quantity: 80,
    supplier_id: "supp_003",
    created_at: new Date("2023-01-12").toISOString(),
  },
]

export const mockPurchaseOrders = [
  {
    id: uuidv4(),
    po_number: "PO-2023-001",
    supplier_id: "supp_001",
    buyer_id: "buyer_001",
    subject: "Initial Stock Order - Wireless Earbuds",
    items: [{ product_id: "prod_001", product_name: "Wireless Earbuds", quantity: 100, unit_price: 75.0 }],
    total_amount: 7500.0,
    status: "sent" as const,
    created_at: new Date("2023-03-01T10:00:00Z").toISOString(),
    sent_at: new Date("2023-03-02T11:00:00Z").toISOString(),
    expected_delivery_date: new Date("2023-03-09T00:00:00Z").toISOString(),
    negotiation_terms: "Standard 30-day payment terms, 2% discount for early payment.",
  },
  {
    id: uuidv4(),
    po_number: "PO-2023-002",
    supplier_id: "supp_002",
    buyer_id: "buyer_002",
    subject: "Restock Order - Smartwatch X",
    items: [{ product_id: "prod_002", product_name: "Smartwatch X", quantity: 50, unit_price: 190.0 }],
    total_amount: 9500.0,
    status: "draft" as const,
    created_at: new Date("2023-03-05T14:30:00Z").toISOString(),
    sent_at: null,
    expected_delivery_date: null,
    negotiation_terms: "Seeking 5% bulk discount for orders over 50 units.",
  },
  {
    id: uuidv4(),
    po_number: "PO-2023-003",
    supplier_id: "supp_001",
    buyer_id: "buyer_001",
    subject: "Portable Speaker Replenishment",
    items: [{ product_id: "prod_003", product_name: "Portable Bluetooth Speaker", quantity: 200, unit_price: 45.0 }],
    total_amount: 9000.0,
    status: "received" as const,
    created_at: new Date("2023-02-10T09:00:00Z").toISOString(),
    sent_at: new Date("2023-02-11T10:00:00Z").toISOString(),
    expected_delivery_date: new Date("2023-02-18T00:00:00Z").toISOString(),
    negotiation_terms: "Net 60 payment terms.",
  },
  {
    id: uuidv4(),
    po_number: "PO-2023-004",
    supplier_id: "supp_003",
    buyer_id: "buyer_003",
    subject: "New Office Chair Order",
    items: [{ product_id: "prod_004", product_name: "Ergonomic Office Chair", quantity: 30, unit_price: 240.0 }],
    total_amount: 7200.0,
    status: "pending" as const,
    created_at: new Date("2023-03-15T16:00:00Z").toISOString(),
    sent_at: new Date("2023-03-16T09:00:00Z").toISOString(),
    expected_delivery_date: new Date("2023-03-30T00:00:00Z").toISOString(),
    negotiation_terms: "Free shipping for orders over $5000.",
  },
]

export const mockReturnItems = [
  {
    id: uuidv4(),
    order_id: "order_abc",
    product_id: "prod_002",
    product_name: "Smartwatch X",
    return_reason: "Defective",
    purchase_date: "2023-01-20",
    category: "Electronics",
    notes: "Screen flickering intermittently.",
    condition: "damaged",
    images: ["/placeholder.svg?height=100&width=100"],
    eligibility_status: "pending",
    classification_ai: null,
    resale_platform_ai: null,
    created_at: new Date("2023-02-01").toISOString(),
  },
  {
    id: uuidv4(),
    order_id: "order_def",
    product_id: "prod_001",
    product_name: "Wireless Earbuds",
    return_reason: "Changed mind",
    purchase_date: "2023-02-10",
    category: "Audio",
    notes: "Customer decided they preferred over-ear headphones.",
    condition: "new",
    images: [],
    eligibility_status: "approved",
    classification_ai: "Resalable",
    resale_platform_ai: "Direct-to-consumer website",
    created_at: new Date("2023-02-15").toISOString(),
  },
  {
    id: uuidv4(),
    order_id: "order_ghi",
    product_id: "prod_003",
    product_name: "Portable Bluetooth Speaker",
    return_reason: "Not as described",
    purchase_date: "2023-03-01",
    category: "Audio",
    notes: "Sound quality not as expected.",
    condition: "used",
    images: ["/placeholder.svg?height=100&width=100"],
    eligibility_status: "rejected",
    classification_ai: "Refurbishable",
    resale_platform_ai: "Electronics Refurbisher",
    created_at: new Date("2023-03-05").toISOString(),
  },
]
